In [2]:
import numpy as np
import pandas as pd

from matplotlib import pyplot as plot

In [2]:
# Install libraries
# !pip install numpy
# !conda install numpy

# Basic data types and nd arrays

In [3]:
# Lists
a_list = [0, 1, 2, 3, 4]

print(a_list)
print(len(a_list))

[0, 1, 2, 3, 4]
5


In [4]:
# List of lists
list_of_lists = [[0, 1, 2, 3, 4],
                 [5, 6, 7, 8, 9]]

print("List_of_lists contains:", list_of_lists)
print("The first element of list_of_lists is:", list_of_lists[0]) # Remember, python indexes from 0
print("The first element in the first element of list_of_lists is:", list_of_lists[0][0])

print(len(list_of_lists))
print(len(list_of_lists[0]))

List_of_lists contains: [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
The first element of list_of_lists is: [0, 1, 2, 3, 4]
The first element in the first element of list_of_lists is: 0
2
5


In [5]:
# Numeric: scalar, vector, and matrix (numpy arrays)
an_int = 2
a_real = 3.1416

print(f"The value of 'an_int' is: {an_int}")
print(f"The value if 'a_real' is: {a_real:3.2f}")

vector = np.array([0, 1, 2, 3])
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

print(f'shape of "vector": {vector.shape}')
print(f'shape of "matrix": {matrix.shape}')

The value of 'an_int' is: 2
The value if 'a_real' is: 3.14
shape of "vector": (4,)
shape of "matrix": (4, 3)


In [8]:
# Difference between vector and 1-D matrix
mat1D = vector.reshape((-1, 1)) # c2 = c.reshape((len(c), 1))

print(f'shape of mat1D: {mat1D.shape}')

shape of mat1D: (4, 1)


In [9]:
# See variables in workspace
%whos

Variable        Type       Data/Info
------------------------------------
a_list          list       n=5
a_real          float      3.1416
an_int          int        2
list_of_lists   list       n=2
mat1D           ndarray    4x1: 4 elems, type `int32`, 16 bytes
matrix          ndarray    4x3: 12 elems, type `int32`, 48 bytes
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pd              module     <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
plot            module     <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
vector          ndarray    4: 4 elems, type `int32`, 16 bytes


In [13]:
# For loop
for it_ in range(10):
    print(it_, end=', ')
    
range_list = list(range(10))
print(range_list)

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
# Save a FOR loop into a list
it_list = [] # initialize empty list
for it_ in range(10):
    it_list.append(it_)

print(it_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
# List comprehension: square of ints
compr_list = [it_**2 for it_ in range(10)]
compr_list

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [18]:
# Heterogeneous list
het_list = [True, "2", 3.14, 2]
print(het_list)

het_list[0] = False
print(het_list)

[True, '2', 3.14, 2]
[False, '2', 3.14, 2]


In [15]:
# Print data types
[type(item) for item in het_list]

[bool, str, float, int]

In [20]:
# Typles: unchangeable
tuple1 = ("apple", "banana", "cherry")
print(tuple1)

tuple1[0] = "pear"
print(tuple1)

('apple', 'banana', 'cherry')


TypeError: 'tuple' object does not support item assignment

In [21]:
# Sets: unordered (unindexed), unchangeable
set1 = {"apple", "banana", "cherry"}
print(set1)
print(set1[0])

{'apple', 'banana', 'cherry'}


TypeError: 'set' object is not subscriptable

In [24]:
# Dictionaries
dict1 = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}
print(dict1)

dict1["year"] = 1956
print(dict1)

dict1[0]

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang', 'year': 1956}


KeyError: 0

# Numpy nd arrays

In [25]:
# Zeros, Ones, Identity and Random
z = np.zeros((2, 3))
print(z)

o = np.ones((2, 3))
print(o)

I = np.eye(5)
print(I)

L = np.linspace(0, 10, 21)
print(L)

R = np.random.random((3, 2))
print(R)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
[[0.28954523 0.61070623]
 [0.0912203  0.64021587]
 [0.40170788 0.77083494]]


In [27]:
# Indexing
print(R[0, 1])
print(R[0][1])

0.6107062270411061
0.6107062270411061


In [31]:
# Slicing
print(R[1:3])
print(R[1:])
print(R[1:2])

[[0.0912203  0.64021587]
 [0.40170788 0.77083494]]
[[0.0912203  0.64021587]
 [0.40170788 0.77083494]]
[[0.0912203  0.64021587]]


In [35]:
# Slicing
print(R[:2])
print(R[:2, 1])

[[0.28954523 0.61070623]
 [0.0912203  0.64021587]]
[0.61070623 0.64021587]


In [36]:
# Concatenation # You can look at np.split
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

np.concatenate([a, b])

array([1, 2, 3, 3, 2, 1])

In [38]:
# Indexing
rand = np.random.randint(100, size=10)
print(rand)

ind = [3, 5, 7]
print(rand[ind])

[ 6  6 22 89 48 95 47 53 34 91]
[89 95 53]


In [39]:
# Indexing
ind = np.array([[3, 7],
                [4, 5]])
print(rand[ind])

[[89 53]
 [48 95]]


In [41]:
# Indexing
rand = np.arange(12).reshape((3, 4))
print(rand)

row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
rand[row, col]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 2,  5, 11])

In [45]:
# Boolean comparison
T = rand > 5
print(T)
print(T.sum())

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
6


In [46]:
# Mask indexing with boolean indices
print(rand[T])
print(rand[T].mean())

[ 6  7  8  9 10 11]
8.5


In [47]:
# functions
def rare_square(x, c):
    y = x**x + c
    return y

In [48]:
# Use funcion
y = rare_square(2, 1)
print(y)

5


# Pandas dataframes

In [49]:
# Load dataset
df = pd.read_csv('train-titanic.csv')
print(df.shape)
df.head()

(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [51]:
# Print name of columns
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [52]:
# Get rid of useless variables
df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [55]:
df[['Survived', 'Age', 'Cabin']]

Survived   Age Cabin
0           0  22.0   NaN
1           1  38.0   C85
2           1  26.0   NaN
3           1  35.0  C123
4           0  35.0   NaN
..        ...   ...   ...
886         0  27.0   NaN
887         1  19.0   B42
888         0   NaN   NaN
889         1  26.0  C148
890         0  32.0   NaN

[891 rows x 3 columns]

In [53]:
# Print a statistical summary (for numeric variables)
df.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [54]:
# Compute stats
df['Fare'].mean()

32.204207968574636

In [56]:
# List comprehension by dictionaries, inside a DataFrame
data = [{'a': i, 'b': 2 * i} for i in range(6)]
pd.DataFrame(data)

a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10

In [59]:
# Indexing
print(df['Fare'][1])
print(df.Fare[1])

71.2833
71.2833


In [60]:
# Slicing
print(df['Fare'][1:5])

1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64


In [67]:
# Explicit index (label indexing and can access multiple columns)
df.loc[df['Sex']=='male']

Survived  Pclass   Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3  male  22.0      1      0   7.2500   NaN        S
4           0       3  male  35.0      0      0   8.0500   NaN        S
5           0       3  male   NaN      0      0   8.4583   NaN        Q
6           0       1  male  54.0      0      0  51.8625   E46        S
7           0       3  male   2.0      3      1  21.0750   NaN        S
..        ...     ...   ...   ...    ...    ...      ...   ...      ...
883         0       2  male  28.0      0      0  10.5000   NaN        S
884         0       3  male  25.0      0      0   7.0500   NaN        S
886         0       2  male  27.0      0      0  13.0000   NaN        S
889         1       1  male  26.0      0      0  30.0000  C148        C
890         0       3  male  32.0      0      0   7.7500   NaN        Q

[577 rows x 9 columns]

In [68]:
# Explicit index slicing
df.loc[(df['Sex']=='male') & (df['Embarked']=='S')]

Survived  Pclass   Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3  male  22.0      1      0   7.2500   NaN        S
4           0       3  male  35.0      0      0   8.0500   NaN        S
6           0       1  male  54.0      0      0  51.8625   E46        S
7           0       3  male   2.0      3      1  21.0750   NaN        S
12          0       3  male  20.0      0      0   8.0500   NaN        S
..        ...     ...   ...   ...    ...    ...      ...   ...      ...
878         0       3  male   NaN      0      0   7.8958   NaN        S
881         0       3  male  33.0      0      0   7.8958   NaN        S
883         0       2  male  28.0      0      0  10.5000   NaN        S
884         0       3  male  25.0      0      0   7.0500   NaN        S
886         0       2  male  27.0      0      0  13.0000   NaN        S

[441 rows x 9 columns]

In [74]:
# More loc slicing
df.loc[0:5, ['Sex', 'Age']]

Sex   Age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0
5    male   NaN

In [76]:
# Implicit indexing (integer indexing)
df.iloc[0, 1]

3

In [77]:
# Implicit slicing
df.iloc[0:4, 2:5]

Sex   Age  SibSp
0    male  22.0      1
1  female  38.0      1
2  female  26.0      0
3  female  35.0      1

In [4]:
# Merge using a key-column
df1 = pd.DataFrame( [{'a': i, 'b': 2 * i} for i in range(6)])
df2 = pd.DataFrame( [{'a': i, 'b': i**2} for i in range(6)])

df3 = pd.merge(df1, df2, on='a')

print(df1)
print(df2)
print(df3)

   a   b
0  0   0
1  1   2
2  2   4
3  3   6
4  4   8
5  5  10
   a   b
0  0   0
1  1   1
2  2   4
3  3   9
4  4  16
5  5  25
   a  b_x  b_y
0  0    0    0
1  1    2    1
2  2    4    4
3  3    6    9
4  4    8   16
5  5   10   25
